// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230208100358_SeedMigration")]
    partial class SeedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steel",
                            Url = "Steel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steel",
                            Url = "Steel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wooden",
                            Url = "Wooden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Steel",
                            Url = "Steel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Plastic",
                            Url = "Plastic"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "orange",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=563010547",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Tasty Fresh Chair"
                        },
                        new
                        {
                            Id = 2,
                            Color = "red",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1809588757",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Generic Cotton Chair"
                        },
                        new
                        {
                            Id = 3,
                            Color = "fuchsia",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=769361000",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Awesome Cotton Soap"
                        },
                        new
                        {
                            Id = 4,
                            Color = "sky blue",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2003116535",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Awesome Granite Chicken"
                        },
                        new
                        {
                            Id = 5,
                            Color = "lavender",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=589837018",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Awesome Cotton Pizza"
                        },
                        new
                        {
                            Id = 6,
                            Color = "azure",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=887835025",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Ergonomic Fresh Table"
                        },
                        new
                        {
                            Id = 7,
                            Color = "azure",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1505479811",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Rustic Concrete Bike"
                        },
                        new
                        {
                            Id = 8,
                            Color = "black",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1927398316",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Awesome Frozen Pants"
                        },
                        new
                        {
                            Id = 9,
                            Color = "indigo",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=281839784",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Awesome Granite Pizza"
                        },
                        new
                        {
                            Id = 10,
                            Color = "cyan",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=864803724",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Refined Steel Sausages"
                        },
                        new
                        {
                            Id = 11,
                            Color = "turquoise",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1016588364",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Unbranded Metal Table"
                        },
                        new
                        {
                            Id = 12,
                            Color = "red",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=155275142",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Sleek Cotton Soap"
                        },
                        new
                        {
                            Id = 13,
                            Color = "gold",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=399048781",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Gorgeous Concrete Shirt"
                        },
                        new
                        {
                            Id = 14,
                            Color = "maroon",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUrl = "https://loremflickr.com/320/240?lock=994885392",
                            MaterialCategoryId = 5,
                            Premium = true,
                            Title = "Fantastic Rubber Mouse"
                        },
                        new
                        {
                            Id = 15,
                            Color = "maroon",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1186284245",
                            MaterialCategoryId = 3,
                            Premium = true,
                            Title = "Intelligent Wooden Cheese"
                        },
                        new
                        {
                            Id = 16,
                            Color = "cyan",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1891470460",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Handmade Rubber Towels"
                        },
                        new
                        {
                            Id = 17,
                            Color = "black",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1801587928",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Awesome Metal Bacon"
                        },
                        new
                        {
                            Id = 18,
                            Color = "pink",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=277508801",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Intelligent Steel Keyboard"
                        },
                        new
                        {
                            Id = 19,
                            Color = "grey",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1220573565",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Handmade Cotton Gloves"
                        },
                        new
                        {
                            Id = 20,
                            Color = "olive",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1145472902",
                            MaterialCategoryId = 2,
                            Premium = false,
                            Title = "Small Steel Hat"
                        },
                        new
                        {
                            Id = 21,
                            Color = "orchid",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUrl = "https://loremflickr.com/320/240?lock=29403447",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Incredible Cotton Towels"
                        },
                        new
                        {
                            Id = 22,
                            Color = "orange",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUrl = "https://loremflickr.com/320/240?lock=516429187",
                            MaterialCategoryId = 4,
                            Premium = false,
                            Title = "Sleek Concrete Table"
                        },
                        new
                        {
                            Id = 23,
                            Color = "olive",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1385658432",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Practical Fresh Keyboard"
                        },
                        new
                        {
                            Id = 24,
                            Color = "orchid",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUrl = "https://loremflickr.com/320/240?lock=221020649",
                            MaterialCategoryId = 3,
                            Premium = false,
                            Title = "Tasty Steel Pizza"
                        },
                        new
                        {
                            Id = 25,
                            Color = "blue",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUrl = "https://loremflickr.com/320/240?lock=35308201",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Incredible Frozen Computer"
                        },
                        new
                        {
                            Id = 26,
                            Color = "gold",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1062899049",
                            MaterialCategoryId = 1,
                            Premium = false,
                            Title = "Generic Wooden Mouse"
                        },
                        new
                        {
                            Id = 27,
                            Color = "silver",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2145371975",
                            MaterialCategoryId = 2,
                            Premium = true,
                            Title = "Refined Cotton Chair"
                        },
                        new
                        {
                            Id = 28,
                            Color = "ivory",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1193987125",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Refined Rubber Hat"
                        },
                        new
                        {
                            Id = 29,
                            Color = "black",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUrl = "https://loremflickr.com/320/240?lock=2097256891",
                            MaterialCategoryId = 1,
                            Premium = true,
                            Title = "Small Metal Soap"
                        },
                        new
                        {
                            Id = 30,
                            Color = "orange",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUrl = "https://loremflickr.com/320/240?lock=1803682168",
                            MaterialCategoryId = 5,
                            Premium = false,
                            Title = "Licensed Concrete Salad"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.ProductAdjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductAdjectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intelligent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Practical"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Refined"
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product_ProductAdjective", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdjectiveId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ProductId", "ProductAdjectiveId");

                    b.HasIndex("ProductAdjectiveId");

                    b.ToTable("Product_ProductAdjectives");

                    b.HasData(
                        new
                        {
                            ProductId = 15,
                            ProductAdjectiveId = 1,
                            Price = 981m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductAdjectiveId = 2,
                            Price = 370m
                        },
                        new
                        {
                            ProductId = 30,
                            ProductAdjectiveId = 3,
                            Price = 133m
                        },
                        new
                        {
                            ProductId = 17,
                            ProductAdjectiveId = 3,
                            Price = 395m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductAdjectiveId = 3,
                            Price = 513m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductAdjectiveId = 3,
                            Price = 500m
                        },
                        new
                        {
                            ProductId = 23,
                            ProductAdjectiveId = 3,
                            Price = 671m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductAdjectiveId = 1,
                            Price = 661m
                        },
                        new
                        {
                            ProductId = 17,
                            ProductAdjectiveId = 1,
                            Price = 250m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 1,
                            Price = 677m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductAdjectiveId = 1,
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductAdjectiveId = 3,
                            Price = 913m
                        },
                        new
                        {
                            ProductId = 21,
                            ProductAdjectiveId = 2,
                            Price = 181m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductAdjectiveId = 2,
                            Price = 615m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductAdjectiveId = 3,
                            Price = 326m
                        },
                        new
                        {
                            ProductId = 14,
                            ProductAdjectiveId = 3,
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductAdjectiveId = 2,
                            Price = 704m
                        },
                        new
                        {
                            ProductId = 24,
                            ProductAdjectiveId = 2,
                            Price = 518m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductAdjectiveId = 1,
                            Price = 611m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductAdjectiveId = 1,
                            Price = 122m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductAdjectiveId = 1,
                            Price = 711m
                        },
                        new
                        {
                            ProductId = 14,
                            ProductAdjectiveId = 1,
                            Price = 48m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductAdjectiveId = 2,
                            Price = 591m
                        },
                        new
                        {
                            ProductId = 25,
                            ProductAdjectiveId = 2,
                            Price = 676m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductAdjectiveId = 3,
                            Price = 8m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductAdjectiveId = 2,
                            Price = 934m
                        },
                        new
                        {
                            ProductId = 28,
                            ProductAdjectiveId = 1,
                            Price = 464m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductAdjectiveId = 2,
                            Price = 76m
                        },
                        new
                        {
                            ProductId = 21,
                            ProductAdjectiveId = 1,
                            Price = 480m
                        },
                        new
                        {
                            ProductId = 18,
                            ProductAdjectiveId = 2,
                            Price = 677m
                        },
                        new
                        {
                            ProductId = 24,
                            ProductAdjectiveId = 3,
                            Price = 771m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductAdjectiveId = 1,
                            Price = 835m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductAdjectiveId = 3,
                            Price = 594m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductAdjectiveId = 2,
                            Price = 812m
                        },
                        new
                        {
                            ProductId = 27,
                            ProductAdjectiveId = 1,
                            Price = 935m
                        },
                        new
                        {
                            ProductId = 22,
                            ProductAdjectiveId = 1,
                            Price = 72m
                        },
                        new
                        {
                            ProductId = 12,
                            ProductAdjectiveId = 2,
                            Price = 633m
                        },
                        new
                        {
                            ProductId = 18,
                            ProductAdjectiveId = 3,
                            Price = 132m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductAdjectiveId = 1,
                            Price = 620m
                        },
                        new
                        {
                            ProductId = 27,
                            ProductAdjectiveId = 3,
                            Price = 304m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductAdjectiveId = 2,
                            Price = 657m
                        },
                        new
                        {
                            ProductId = 25,
                            ProductAdjectiveId = 3,
                            Price = 85m
                        },
                        new
                        {
                            ProductId = 28,
                            ProductAdjectiveId = 3,
                            Price = 661m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductAdjectiveId = 1,
                            Price = 408m
                        });
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.HasOne("P05Sklep.Shared.MaterialCategory", "MaterialCategory")
                        .WithMany()
                        .HasForeignKey("MaterialCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialCategory");
                });

            modelBuilder.Entity("P05Sklep.Shared.Product_ProductAdjective", b =>
                {
                    b.HasOne("P05Sklep.Shared.ProductAdjective", "ProductAdjective")
                        .WithMany()
                        .HasForeignKey("ProductAdjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P05Sklep.Shared.Product", "Product")
                        .WithMany("product_ProductAdjectives")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAdjective");
                });

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Navigation("product_ProductAdjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
